# This rule is not used by the project pulse itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over canary.iambarton.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pulse
    app.kubernetes.io/managed-by: kustomize
  name: grpccanary-admin-role
rules:
- apiGroups:
  - canary.iambarton.com
  resources:
  - grpccanaries
  verbs:
  - '*'
- apiGroups:
  - canary.iambarton.com
  resources:
  - grpccanaries/status
  verbs:
  - get
