# Example HttpCanary that is expected to fail health checks.
apiVersion: canary.iambarton.com/v1alpha1
kind: HttpCanary
metadata:
  name: sample-http-check-unhealthy
  namespace: default
spec:
  url: "https://httpbin.org/status/503"
  interval: 30
  expectedStatus: 200
