//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyAction) DeepCopyInto(out *AnomalyAction) {
	*out = *in
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(LLMAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ObservabilityAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyAction.
func (in *AnomalyAction) DeepCopy() *AnomalyAction {
	if in == nil {
		return nil
	}
	out := new(AnomalyAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyIncidents) DeepCopyInto(out *AnomalyIncidents) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyIncidents.
func (in *AnomalyIncidents) DeepCopy() *AnomalyIncidents {
	if in == nil {
		return nil
	}
	out := new(AnomalyIncidents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyModelConfig) DeepCopyInto(out *AnomalyModelConfig) {
	*out = *in
	if in.Hot != nil {
		in, out := &in.Hot, &out.Hot
		*out = new(HotModelConfig)
		**out = **in
	}
	if in.Cold != nil {
		in, out := &in.Cold, &out.Cold
		*out = new(ColdModelConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyModelConfig.
func (in *AnomalyModelConfig) DeepCopy() *AnomalyModelConfig {
	if in == nil {
		return nil
	}
	out := new(AnomalyModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyPolicy) DeepCopyInto(out *AnomalyPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyPolicy.
func (in *AnomalyPolicy) DeepCopy() *AnomalyPolicy {
	if in == nil {
		return nil
	}
	out := new(AnomalyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnomalyPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyPolicyList) DeepCopyInto(out *AnomalyPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnomalyPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyPolicyList.
func (in *AnomalyPolicyList) DeepCopy() *AnomalyPolicyList {
	if in == nil {
		return nil
	}
	out := new(AnomalyPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnomalyPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyPolicySpec) DeepCopyInto(out *AnomalyPolicySpec) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(AnomalyModelConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = new(AnomalyTriggers)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(AnomalyTopology)
		(*in).DeepCopyInto(*out)
	}
	if in.Incidents != nil {
		in, out := &in.Incidents, &out.Incidents
		*out = new(AnomalyIncidents)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]AnomalyAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Throttle != nil {
		in, out := &in.Throttle, &out.Throttle
		*out = new(AnomalyThrottle)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyPolicySpec.
func (in *AnomalyPolicySpec) DeepCopy() *AnomalyPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AnomalyPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyPolicyStatus) DeepCopyInto(out *AnomalyPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InferredDependencies != nil {
		in, out := &in.InferredDependencies, &out.InferredDependencies
		*out = make([]InferredDependency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyPolicyStatus.
func (in *AnomalyPolicyStatus) DeepCopy() *AnomalyPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AnomalyPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyThrottle) DeepCopyInto(out *AnomalyThrottle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyThrottle.
func (in *AnomalyThrottle) DeepCopy() *AnomalyThrottle {
	if in == nil {
		return nil
	}
	out := new(AnomalyThrottle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyTopology) DeepCopyInto(out *AnomalyTopology) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]CanaryDependency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyTopology.
func (in *AnomalyTopology) DeepCopy() *AnomalyTopology {
	if in == nil {
		return nil
	}
	out := new(AnomalyTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyTriggers) DeepCopyInto(out *AnomalyTriggers) {
	*out = *in
	if in.BodyDrift != nil {
		in, out := &in.BodyDrift, &out.BodyDrift
		*out = new(BodyDriftTrigger)
		(*in).DeepCopyInto(*out)
	}
	if in.LatencyShift != nil {
		in, out := &in.LatencyShift, &out.LatencyShift
		*out = new(LatencyShiftTrigger)
		**out = **in
	}
	if in.FailureCorrelation != nil {
		in, out := &in.FailureCorrelation, &out.FailureCorrelation
		*out = new(FailureCorrelationTrigger)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureNovelty != nil {
		in, out := &in.FailureNovelty, &out.FailureNovelty
		*out = new(FailureNoveltyTrigger)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyTriggers.
func (in *AnomalyTriggers) DeepCopy() *AnomalyTriggers {
	if in == nil {
		return nil
	}
	out := new(AnomalyTriggers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyDriftTrigger) DeepCopyInto(out *BodyDriftTrigger) {
	*out = *in
	if in.Redact != nil {
		in, out := &in.Redact, &out.Redact
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyDriftTrigger.
func (in *BodyDriftTrigger) DeepCopy() *BodyDriftTrigger {
	if in == nil {
		return nil
	}
	out := new(BodyDriftTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryDependency) DeepCopyInto(out *CanaryDependency) {
	*out = *in
	if in.Upstream != nil {
		in, out := &in.Upstream, &out.Upstream
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryDependency.
func (in *CanaryDependency) DeepCopy() *CanaryDependency {
	if in == nil {
		return nil
	}
	out := new(CanaryDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryIntelligence) DeepCopyInto(out *CanaryIntelligence) {
	*out = *in
	out.PolicyRef = in.PolicyRef
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(TriggerTuning)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryIntelligence.
func (in *CanaryIntelligence) DeepCopy() *CanaryIntelligence {
	if in == nil {
		return nil
	}
	out := new(CanaryIntelligence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryIntelligenceStatus) DeepCopyInto(out *CanaryIntelligenceStatus) {
	*out = *in
	if in.LastSignalTime != nil {
		in, out := &in.LastSignalTime, &out.LastSignalTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryIntelligenceStatus.
func (in *CanaryIntelligenceStatus) DeepCopy() *CanaryIntelligenceStatus {
	if in == nil {
		return nil
	}
	out := new(CanaryIntelligenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColdModelConfig) DeepCopyInto(out *ColdModelConfig) {
	*out = *in
	if in.ONNX != nil {
		in, out := &in.ONNX, &out.ONNX
		*out = new(ONNXModelConfig)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPEmbeddingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColdModelConfig.
func (in *ColdModelConfig) DeepCopy() *ColdModelConfig {
	if in == nil {
		return nil
	}
	out := new(ColdModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureCorrelationTrigger) DeepCopyInto(out *FailureCorrelationTrigger) {
	*out = *in
	if in.CandidateSelector != nil {
		in, out := &in.CandidateSelector, &out.CandidateSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureCorrelationTrigger.
func (in *FailureCorrelationTrigger) DeepCopy() *FailureCorrelationTrigger {
	if in == nil {
		return nil
	}
	out := new(FailureCorrelationTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureNoveltyTrigger) DeepCopyInto(out *FailureNoveltyTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureNoveltyTrigger.
func (in *FailureNoveltyTrigger) DeepCopy() *FailureNoveltyTrigger {
	if in == nil {
		return nil
	}
	out := new(FailureNoveltyTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCanary) DeepCopyInto(out *GrpcCanary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCanary.
func (in *GrpcCanary) DeepCopy() *GrpcCanary {
	if in == nil {
		return nil
	}
	out := new(GrpcCanary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrpcCanary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCanaryList) DeepCopyInto(out *GrpcCanaryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GrpcCanary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCanaryList.
func (in *GrpcCanaryList) DeepCopy() *GrpcCanaryList {
	if in == nil {
		return nil
	}
	out := new(GrpcCanaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrpcCanaryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCanarySpec) DeepCopyInto(out *GrpcCanarySpec) {
	*out = *in
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]HttpCanaryOutput, len(*in))
		copy(*out, *in)
	}
	if in.Intelligence != nil {
		in, out := &in.Intelligence, &out.Intelligence
		*out = new(CanaryIntelligence)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCanarySpec.
func (in *GrpcCanarySpec) DeepCopy() *GrpcCanarySpec {
	if in == nil {
		return nil
	}
	out := new(GrpcCanarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCanaryStatus) DeepCopyInto(out *GrpcCanaryStatus) {
	*out = *in
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Intelligence != nil {
		in, out := &in.Intelligence, &out.Intelligence
		*out = new(CanaryIntelligenceStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCanaryStatus.
func (in *GrpcCanaryStatus) DeepCopy() *GrpcCanaryStatus {
	if in == nil {
		return nil
	}
	out := new(GrpcCanaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPEmbeddingConfig) DeepCopyInto(out *HTTPEmbeddingConfig) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPEmbeddingConfig.
func (in *HTTPEmbeddingConfig) DeepCopy() *HTTPEmbeddingConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPEmbeddingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotModelConfig) DeepCopyInto(out *HotModelConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotModelConfig.
func (in *HotModelConfig) DeepCopy() *HotModelConfig {
	if in == nil {
		return nil
	}
	out := new(HotModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanary) DeepCopyInto(out *HttpCanary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanary.
func (in *HttpCanary) DeepCopy() *HttpCanary {
	if in == nil {
		return nil
	}
	out := new(HttpCanary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HttpCanary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryAPIKeyAuth) DeepCopyInto(out *HttpCanaryAPIKeyAuth) {
	*out = *in
	in.ValueSecretRef.DeepCopyInto(&out.ValueSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryAPIKeyAuth.
func (in *HttpCanaryAPIKeyAuth) DeepCopy() *HttpCanaryAPIKeyAuth {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryAPIKeyAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryAuth) DeepCopyInto(out *HttpCanaryAuth) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(HttpCanaryBasicAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.Bearer != nil {
		in, out := &in.Bearer, &out.Bearer
		*out = new(HttpCanaryBearerAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(HttpCanaryAPIKeyAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryAuth.
func (in *HttpCanaryAuth) DeepCopy() *HttpCanaryAuth {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryBasicAuth) DeepCopyInto(out *HttpCanaryBasicAuth) {
	*out = *in
	in.UsernameSecretRef.DeepCopyInto(&out.UsernameSecretRef)
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryBasicAuth.
func (in *HttpCanaryBasicAuth) DeepCopy() *HttpCanaryBasicAuth {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryBearerAuth) DeepCopyInto(out *HttpCanaryBearerAuth) {
	*out = *in
	in.TokenSecretRef.DeepCopyInto(&out.TokenSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryBearerAuth.
func (in *HttpCanaryBearerAuth) DeepCopy() *HttpCanaryBearerAuth {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryBearerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryList) DeepCopyInto(out *HttpCanaryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HttpCanary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryList.
func (in *HttpCanaryList) DeepCopy() *HttpCanaryList {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HttpCanaryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryMCP) DeepCopyInto(out *HttpCanaryMCP) {
	*out = *in
	if in.RequiredTools != nil {
		in, out := &in.RequiredTools, &out.RequiredTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryMCP.
func (in *HttpCanaryMCP) DeepCopy() *HttpCanaryMCP {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryMCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryOutput) DeepCopyInto(out *HttpCanaryOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryOutput.
func (in *HttpCanaryOutput) DeepCopy() *HttpCanaryOutput {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanarySpec) DeepCopyInto(out *HttpCanarySpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(HttpCanaryAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(HttpCanaryMCP)
		(*in).DeepCopyInto(*out)
	}
	if in.Journey != nil {
		in, out := &in.Journey, &out.Journey
		*out = make([]HttpCanaryStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]HttpCanaryOutput, len(*in))
		copy(*out, *in)
	}
	if in.Intelligence != nil {
		in, out := &in.Intelligence, &out.Intelligence
		*out = new(CanaryIntelligence)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanarySpec.
func (in *HttpCanarySpec) DeepCopy() *HttpCanarySpec {
	if in == nil {
		return nil
	}
	out := new(HttpCanarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryStatus) DeepCopyInto(out *HttpCanaryStatus) {
	*out = *in
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.Intelligence != nil {
		in, out := &in.Intelligence, &out.Intelligence
		*out = new(CanaryIntelligenceStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryStatus.
func (in *HttpCanaryStatus) DeepCopy() *HttpCanaryStatus {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpCanaryStep) DeepCopyInto(out *HttpCanaryStep) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpCanaryStep.
func (in *HttpCanaryStep) DeepCopy() *HttpCanaryStep {
	if in == nil {
		return nil
	}
	out := new(HttpCanaryStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferredDependency) DeepCopyInto(out *InferredDependency) {
	*out = *in
	if in.LastObserved != nil {
		in, out := &in.LastObserved, &out.LastObserved
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferredDependency.
func (in *InferredDependency) DeepCopy() *InferredDependency {
	if in == nil {
		return nil
	}
	out := new(InferredDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMAction) DeepCopyInto(out *LLMAction) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMAction.
func (in *LLMAction) DeepCopy() *LLMAction {
	if in == nil {
		return nil
	}
	out := new(LLMAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencyShiftTrigger) DeepCopyInto(out *LatencyShiftTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencyShiftTrigger.
func (in *LatencyShiftTrigger) DeepCopy() *LatencyShiftTrigger {
	if in == nil {
		return nil
	}
	out := new(LatencyShiftTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ONNXModelConfig) DeepCopyInto(out *ONNXModelConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ONNXModelConfig.
func (in *ONNXModelConfig) DeepCopy() *ONNXModelConfig {
	if in == nil {
		return nil
	}
	out := new(ONNXModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityAction) DeepCopyInto(out *ObservabilityAction) {
	*out = *in
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityAction.
func (in *ObservabilityAction) DeepCopy() *ObservabilityAction {
	if in == nil {
		return nil
	}
	out := new(ObservabilityAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyReference) DeepCopyInto(out *PolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyReference.
func (in *PolicyReference) DeepCopy() *PolicyReference {
	if in == nil {
		return nil
	}
	out := new(PolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAction) DeepCopyInto(out *SlackAction) {
	*out = *in
	if in.WebhookSecretRef != nil {
		in, out := &in.WebhookSecretRef, &out.WebhookSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BotTokenSecretRef != nil {
		in, out := &in.BotTokenSecretRef, &out.BotTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAction.
func (in *SlackAction) DeepCopy() *SlackAction {
	if in == nil {
		return nil
	}
	out := new(SlackAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerTuning) DeepCopyInto(out *TriggerTuning) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerTuning.
func (in *TriggerTuning) DeepCopy() *TriggerTuning {
	if in == nil {
		return nil
	}
	out := new(TriggerTuning)
	in.DeepCopyInto(out)
	return out
}
